spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET_KEY}
jwt.access-token-validity-seconds=180
jwt.refresh-token-validity-seconds=10800
jwt.issuer=auth-service