services:
  broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    hostname: kafka-broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker:${KAFKA_INTERNAL_PORT},PLAINTEXT_HOST://0.0.0.0:${KAFKA_EXTERNAL_PORT},CONTROLLER://kafka-broker:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:${KAFKA_INTERNAL_PORT},PLAINTEXT_HOST://localhost:${KAFKA_EXTERNAL_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:29093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
    networks:
      - backend

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - backend

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - backend

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8083:8083"
    networks:
      - backend

  cart-service:
    build: ./cart-service
    container_name: cart-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      TOPIC_CHECKOUT: ${TOPIC_CHECKOUT}
    ports:
      - "8084:8084"
    depends_on:
      - product-service
      - broker
    networks:
      - backend

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      TOPIC_CHECKOUT: ${TOPIC_CHECKOUT}
      TOPIC_ORDER_CREATED: ${TOPIC_ORDER_CREATED}
      TOPIC_STOCK_REJECTED: ${TOPIC_STOCK_REJECTED}
    ports:
      - "8085:8085"
    depends_on:
      - product-service
      - broker
    networks:
      - backend

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      TOPIC_ORDER_CREATED: ${TOPIC_ORDER_CREATED}
      TOPIC_ORDER_CANCELLED: ${TOPIC_ORDER_CANCELLED}
      TOPIC_STOCK_REJECTED: ${TOPIC_STOCK_REJECTED}
    ports:
      - "8086:8086"
    depends_on:
      - broker
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
      CART_SERVICE_URL: ${CART_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}
      INVENTORY_SERVICE_URL: ${INVENTORY_SERVICE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
      - product-service
      - cart-service
      - order-service
      - inventory-service
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      args:
          VITE_GATEWAY_URL: ${GATEWAY_URL}
    container_name: frontend
    environment:
      VITE_GATEWAY_URL: ${GATEWAY_URL}
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - frontend

networks:
  backend:
  frontend:
