server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}

spring:
  application:
    name: spring-api-gateway
  cloud:
    gateway:
      server:
        web flux:
          global cors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - ${FRONTEND_URL}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - Authorization
                  - Content-Type
                exposedHeaders:
                  - Set-Cookie
                allowCredentials: true
            default-filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s
          routes:
          # Auth route
            - id: auth-service
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/auth/{segment:register|login|refresh|logout}
              filters:
                - RewritePath=/auth/(?<segment>register|login|refresh|logout), /auth/${segment}
          # public routes
            - id: product-service
              uri: ${PRODUCT_SERVICE_URL}
              predicates:
                - Path=/products/**
              filters:
                - RewritePath=/products/(?<segment>.*), /api/products/${segment}
            - id: product-images
              uri: ${PRODUCT_SERVICE_URL}
              predicates:
                - Path=/images/**
              filters:
                - RewritePath=/images/(?<segment>.*), /images/${segment}
            - id: inventory-service
              uri: ${INVENTORY_SERVICE_URL}
              predicates:
                - Path=/inventory/**
              filters:
                - RewritePath=/inventory/(?<segment>.*), /api/inventory/${segment}
          # protected routes
            - id: user-service
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/user/**
              filters:
                - JwtAuth
                - name: RoleCheck
                  args:
                    requiredRoles: ROLE_USER,ROLE_ADMIN
                - RewritePath=/user/(?<segment>.*), /api/user/${segment}
            - id: cart-service
              uri: ${CART_SERVICE_URL}
              predicates:
                - Path=/cart/**
              filters:
                - JwtAuth
                - name: RoleCheck
                  args:
                    requiredRoles: ROLE_USER,ROLE_ADMIN
                - RewritePath=/cart/(?<segment>.*), /api/cart/${segment}
            - id: order-service
              uri: ${ORDER_SERVICE_URL}
              predicates:
                - Path=/orders/**
              filters:
                - JwtAuth
                - name: RoleCheck
                  args:
                    requiredRoles: ROLE_USER,ROLE_ADMIN
                - RewritePath=/orders/(?<segment>.*), /api/orders/${segment}
