INSERT INTO products (id, title, price, cover_image_url, description, sku, type)
VALUES
    ('g1', 'Elden Ring', 59.99, 'elden_ring.jpg', 'Elden Ring is an expansive action RPG set across the vast Lands Between, where players explore open fields, hidden dungeons, and towering legacy castles while uncovering the mysteries of the shattered Elden Ring. As a Tarnished, you''ll battle powerful foes, master diverse weapons and magic, and forge your own path through a world shaped by ruin, ambition, and ancient gods.',
        'SKU-ER', 'GAME'),
    ('g2', 'Halo Infinite', 49.99, 'halo_infinite.jpg',
     'Halo Infinite sends Master Chief into a new conflict on a damaged Halo ring, blending open-world exploration with fast, tactical combat. As the Banished tighten their grip, you uncover secrets, liberate outposts, and fight to restore hope for humanity across the vast terrain of Zeta Halo.',
         'SKU-HALO', 'GAME'),
    ('g3', 'Skyrim', 39.99, 'skyrim.jpg', 'Skyrim drops you into a vast northern realm filled with ancient ruins, dangerous creatures, and warring factions. As the Dragonborn, you uncover your unique powers while exploring snowy mountains, hidden dungeons, and bustling towns. Your choices shape the world as you battle dragons, master powerful skills, and forge your own path through an open world full of freedom and discovery.',
     'SKU-SKY', 'GAME'),
    ('g4', 'Resident Evil Village', 49.99, 're8.jpg', 'Resident Evil Village follows Ethan Winters into a remote European settlement ruled by terrifying figures and twisted creatures. Searching for his kidnapped daughter, he explores snowy forests, eerie homes, and the towering castle of Lady Dimitrescu while uncovering the dark secrets behind the village''s curse. The game blends tense exploration, survival combat, and atmospheric horror as Ethan fights to escape and protect his family.',
     'SKU-RE8', 'GAME'),
    ('g5', 'Cities: Skylines', 29.99, 'cities.jpg', 'City-building simulation.', 'SKU-CS', 'GAME'),
    ('g6', 'Subnautica', 24.99, 'subnautica.jpg', 'Underwater survival adventure.', 'SKU-SUB', 'GAME'),
    ('g7', 'StarCraft II', 20.00, 'sc2.jpg', 'Sci-fi real-time strategy.', 'SKU-SC2', 'GAME'),
    ('g8', 'FIFA 24', 69.99, 'fifa24.jpg', 'Football sports simulation.', 'SKU-FIFA24', 'GAME'),
    ('g9', 'Forza Horizon 5', 59.99, 'forza5.jpg', 'Open world racing game.', 'SKU-FH5', 'GAME'),
    ('g10', 'God of War Ragnarok', 69.99, 'gowr.jpg', 'Norse action adventure.', 'SKU-GOWR', 'GAME'),
    ('g11', 'Call of Duty: Modern Warfare II', 69.99, 'mw2.jpg', 'Military FPS shooter.', 'SKU-MW2', 'GAME'),
    ('g12', 'Baldur''s Gate 3', 69.99, 'bg3.jpg', 'Deep narrative-driven RPG.', 'SKU-BG3', 'GAME'),
    ('g13', 'Terraria', 9.99, 'terraria.jpg', '2D sandbox exploration.', 'SKU-TERRARIA', 'GAME'),
    ('g14', 'The Sims 4', 19.99, 'sims4.jpg', 'Life simulation game.', 'SKU-SIMS4', 'GAME'),
    ('g15', 'The Forest', 19.99, 'forest.jpg', 'Open world survival horror.', 'SKU-FOREST', 'GAME'),
    ('g16', 'Age of Empires IV', 59.99, 'aoe4.jpg', 'Historical real-time strategy.', 'SKU-AOE4', 'GAME'),
    ('g17', 'NBA 2K24', 69.99, 'nba2k24.jpg', 'Basketball sports simulation.', 'SKU-NBA2K24', 'GAME'),
    ('g18', 'Gran Turismo 7', 69.99, 'gt7.jpg', 'Realistic racing simulator.', 'SKU-GT7', 'GAME'),
    ('g19', 'Horizon Zero Dawn', 39.99, 'hzd.jpg', 'Sci-fi action adventure.', 'SKU-HZD', 'GAME'),
    ('g20', 'Zelda: Breath of the Wild', 59.99, 'botw.jpg', 'Open world action adventure.', 'SKU-BOTW', 'GAME'),
    ('g21', 'Super Mario Odyssey', 49.99, 'mario_odyssey.jpg', '3D platform adventure.', 'SKU-MOD', 'GAME'),
    ('g22', 'Gears 5', 39.99, 'gears5.jpg', 'Third-person shooter.', 'SKU-G5', 'GAME'),
    ('g23', 'Halo Master Chief Collection', 29.99, 'mcc.jpg', 'FPS anthology collection.', 'SKU-MCC', 'GAME'),
    ('g24', 'Spider-Man Remastered', 49.99, 'spiderman_remastered.jpg', 'Open world superhero action.', 'SKU-SMR', 'GAME'),
    ('g25', 'Mario Kart 8 Deluxe', 59.99, 'mk8.jpg', 'Arcade racing game.', 'SKU-MK8', 'GAME'),
    ('g26', 'Metroid Dread', 49.99, 'metroid_dread.jpg', 'Sci-fi action platformer.', 'SKU-MD', 'GAME'),
    ('g27', 'Flight Simulator', 69.99, 'flight_sim.jpg', 'Realistic flight simulation.', 'SKU-FS', 'GAME'),
    ('g28', 'Sea of Thieves', 39.99, 'sea_of_thieves.jpg', 'Co-op pirate adventure.', 'SKU-SOT', 'GAME'),
    ('g29', 'The Last of Us Part I', 69.99, 'tlou1.png', 'The Last of Us Part I follows Joel and Ellie on a dangerous journey across a ravaged United States, where infected creatures and desperate survivors threaten every step. Their bond grows as they navigate abandoned towns, hidden shelters, and brutal encounters, revealing a story of loss, hope, and the lengths people go to protect one another.',
     'SKU-TLOU1', 'GAME'),
    ('g30', 'Super Smash Bros Ultimate', 59.99, 'ssbu.jpg', 'Nintendo fighting crossover.', 'SKU-SSBU', 'GAME');

INSERT INTO games (id, platform, genre, release_date, publisher, developer)
VALUES
    ('g1', 'PC', 'RPG', '2022-02-25', 'Bandai Namco', 'FromSoftware'),
    ('g2', 'XBOX', 'FPS', '2021-12-08', 'Xbox Game Studios', '343 Industries'),
    ('g3', 'PC', 'RPG', '2011-11-11', 'Bethesda', 'Bethesda Game Studios'),
    ('g4', 'PC', 'HORROR', '2021-05-07', 'Capcom', 'Capcom'),
    ('g5', 'PC', 'SIMULATION', '2015-03-10', 'Paradox Interactive', 'Colossal Order'),
    ('g6', 'PC', 'SURVIVAL', '2018-01-23', 'Unknown Worlds', 'Unknown Worlds'),
    ('g7', 'PC', 'STRATEGY', '2010-07-27', 'Blizzard', 'Blizzard'),
    ('g8', 'PC', 'SPORTS', '2023-09-29', 'EA Sports', 'EA Sports'),
    ('g9', 'XBOX', 'RACING', '2021-11-09', 'Xbox Game Studios', 'Playground Games'),
    ('g10', 'PLAYSTATION', 'ACTION', '2022-11-09', 'Sony', 'Santa Monica Studio'),
    ('g11', 'PC', 'FPS', '2022-10-28', 'Activision', 'Infinity Ward'),
    ('g12', 'PC', 'RPG', '2023-08-03', 'Larian Studios', 'Larian Studios'),
    ('g13', 'PC', 'SANDBOX', '2011-05-16', 'Re-Logic', 'Re-Logic'),
    ('g14', 'PC', 'SIMULATION', '2014-09-02', 'EA', 'Maxis'),
    ('g15', 'PC', 'SURVIVAL', '2018-04-30', 'Endnight Games', 'Endnight Games'),
    ('g16', 'PC', 'STRATEGY', '2021-10-28', 'Xbox Game Studios', 'Relic Entertainment'),
    ('g17', 'PC', 'SPORTS', '2023-09-08', '2K Games', 'Visual Concepts'),
    ('g18', 'PLAYSTATION', 'RACING', '2022-03-04', 'Sony', 'Polyphony Digital'),
    ('g19', 'PC', 'ACTION', '2017-02-28', 'Sony', 'Guerrilla Games'),
    ('g20', 'NINTENDO', 'ACTION', '2017-03-03', 'Nintendo', 'Nintendo'),
    ('g21', 'NINTENDO', 'ACTION', '2017-10-27', 'Nintendo', 'Nintendo'),
    ('g22', 'XBOX', 'ACTION', '2019-09-10', 'Xbox Game Studios', 'The Coalition'),
    ('g23', 'XBOX', 'FPS', '2014-11-11', 'Xbox Game Studios', '343 Industries'),
    ('g24', 'PLAYSTATION', 'ACTION', '2020-11-12', 'Sony', 'Insomniac Games'),
    ('g25', 'NINTENDO', 'RACING', '2017-04-28', 'Nintendo', 'Nintendo'),
    ('g26', 'NINTENDO', 'ACTION', '2021-10-08', 'Nintendo', 'MercurySteam'),
    ('g27', 'PC', 'SIMULATION', '2020-08-18', 'Xbox Game Studios', 'Asobo Studio'),
    ('g28', 'XBOX', 'ACTION', '2018-03-20', 'Xbox Game Studios', 'Rare'),
    ('g29', 'PLAYSTATION', 'ACTION', '2020-06-19', 'Sony', 'Naughty Dog'),
    ('g30', 'NINTENDO', 'FIGHTING', '2018-12-07', 'Nintendo', 'Bandai Namco');
