spring.application.name=inventory-service

server.port=8086

spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Broker Config
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.group-id=inventory-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.inventory.dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.inventory.event.OrderCreatedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

topic.order-created=${TOPIC_ORDER_CREATED}
topic.order-cancelled=${TOPIC_ORDER_CANCElLED}
topic.stock-rejected=${TOPIC_STOCK_REJECTED}
